- hosts: all
  gather_facts: false
  tasks:
  - name: Install packages
    package:
      name: ntpdate
      state: absent

  - name: copy files
    copy:
      src: /etc/apt/apt.conf.d/50appstream
      dest: /tmp/tests.apt.d
    notify:
      - startservice

  handlers:
    - name: startservice
      service:
        name: httpd
        state: restarted
