---
- hosts: test1
  tasks:
    - name: Create groups
      group:
        name: wheel
        state: present

    - name: Create serveral users
      user:
        name: "{{ item }}"
        state: present
        groups: "wheel"
      loop:
        - testuser1
        - testuser2
        - testuser3
        - testuser4
        - testuser5
        - testuser6
